language: node_js

node_js:
  - "7"

branches:
  only:
  - master
  - develop
  - "/^v.*$/"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

before_deploy:
  - npm run build-travis

deploy:
  provider: releases
  api_key:
    secure: gHgdamFQGb5UX05AHAtwf/Cv8DqdkoL0ObU9pm3D6ZLLvHfGB7liZp6twWElxihKOAHOqqqJ0Qw3oD1He/0nRZ3Jco64PueZoC82QadCIOqPHv0LAACK609vyC7K1u7X2zQNV+Fxs+YaQn6N+EJW06rBGicTnHFqXAB80jACYEnhuRMOKGMTWLteET2iCofWgm3X5V3Ab5QIQOw5hc4+DtlmbeSWr9AHFrvRerc8Mk/gfQmvpgYDIgqNrGDaV+X4FLuxwLPmuUNlGHKemsZ3+f3x1CRs7JAD+AKUonbTbEByLwWuKG8IKcvXwbNu0FLEWVxbC2ZAMGzPLQFd+WAGf800unDQS5D/Jq7odahzEjPvSiLvfYFtfqS/Z92cySrFmH9KMXcfmQKd9hOtgmCZIKI3zNDBW3o+vaD3kAUYQyuzhhTNUax1xSg2eLcbP6hOD+3braNZApOgv4y6bB++wjV7ldte9AOn4xfnHiVs/vXmLoN1bTc87zDDjLLds8gIwlkQEgBxOeOzn9TcsM5KwvN05ySTIEnULJXN8fzpoW38gQYuNKJS6n77qVaBxQlXp4rex9NanXZdF6Gk6lX9hGNKDZOK8CsqUOUbhVK0Ag6rkMC0Qi2aeSFDvxbdb3ubgSYKIVwXgwtQIP8lkJf19oq1ONoxar0t4gGT4hQSwZs=
  file: build.zip
  skip_cleanup: true
  on:
    repo: flekschas/hipiler
    tags: true
