language: node_js
node_js:
- '8'
branches:
  only:
  - master
  - develop
  - "/^v.*$/"
before_install:
- export CHROME_BIN=chromium-browser
services:
- xvfb
before_script:
- npm install
before_deploy:
- npm run prerelease
deploy:
  provider: releases
  api_key:
    secure: wccs2hgDobPEwKUqzSIWGbDUGUFrGaLMu3NFTttgVgDsXQnqEXBg7XqTHML6yW4vdk1ug/frKvKrasyvTxNZ16kFQWNutUL8wiyoUc9dkYyCOt1oUdH9rv8L4ZhJPC/XQ+Y5A9Yi/V+Imcw+P0woukMQYsbADWFvlJh4FF2ObDklxghUp/KbeaKANrqlRg99JvAcJE0JdADuAbtyJUBzMJPqtaFdGW6q8sJzwdSY1tP18Hk8YWZl+kDErRQW/KA/YMDAkf0S009eeLcy3CZkTT1OcO3TuddboevfgxQnXufbEmDg+O4/gzZN9fSSllBnDM+UUyb4ebzlKmPQmXHcH7ab00IKyNfGUNQJ2g/tfHBPLnuL3k2+NKtLzXASu2Lbkp11Ycsgcb3XGE93Nzf/qaPj7KOz88WpWohTs2y3xbSK6i9xn4bdotL4Af9OgVg6NCNoH5z9NLgJO+bUEdyxXXpCghR5iSGu3bir898PU7pLCU8218VNMGRCREptUneYv58X1CQmqdtzyszfx0UkM8sw3TZS7zJUciEulaJElV7Ab60Cd3JqMgdyL2QpQa9sgqpFgZuVko1RANqFgdCLuk5tubFuBS4ZM68sNx+VB5iqmC7f25ltaviVjI7i+C12ZTpbI3U6l2tpWnW15t3DjZPRHKWzVtwerMAnVmfWEBs=
  file: build.zip
  skip_cleanup: true
  on:
    repo: flekschas/hipiler
    tags: true
