language: node_js

node_js:
  - "8"

branches:
  only:
  - master
  - develop
  - "/^v.*$/"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

before_script:
  - npm install

before_deploy:
  - npm run prerelease

deploy:
  provider: releases
  api_key:
    secure: tdKSO9AWVyis5PRncToYJJ4N82wivD8wDMPfinjqYDZFdI5p0JEuPHKvztM5NAnAfHMmxANbczQgQJEWA69GPy/IiRs3IwBRB9aaN40XYKh7eTOBULZzU+2hhvwxEnEgre0aMlnXy6X2Ughp7jVIMrEay9RhS6jsPCmLZ1LLVkNSDwLpqWz2rN0jxAZHhHqmIEtLVFI+LoF15lqJ5FV0R5JscyuL9zDFLc2aO1Hhczrm+0RofFn7jT7BexbCwCvXC4hUo9IjPjoLWqODYPxwjAgoi6hk+txW1Vs14s0pB7+gvCZtqanbVjQj+68uhvSzZYyOtZpBNE+rXuY5lsJRaE1V9dMiZAOMAPqQJKaoa8DKQWgL9zYX3XiX4Xt4iHokjLZTiOQ/oPbN1bd7rds1GC7b9L9TTALua5sBtqeERKNzs5RZDJz8yFR0KmHCigm1ZBU5rGgUyXSi5DJ/0nmXE5vhlS6wLQzrzLZrD7k2AdyleNe9MDNNXzBi7IahSL3JrN1ml9lV6uKBJgU68BjJjrC9adY7PkH7uLMnNMxI3Wo6sq+chHYAwgatU5mQw9VN1Oy/EHWv4TjXdmuQrsR1eX4xHoeOgmM4ZPKi81EnqeTgYH2g7cDx425kIE2Ov27VngqAxK11JmJA/D/tfRQUd408RqVZr/NEojrz/tw8n5g=
  file: build.zip
  skip_cleanup: true
  on:
    repo: flekschas/hipiler
    tags: true
